# Generated by Django 4.2.7 on 2023-11-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.CharField(max_length=255, verbose_name='Название рецепта')),
                ('preview', models.TextField(max_length=380, verbose_name='Превью рецепта')),
                ('text_post', models.TextField(max_length=4000, verbose_name='Текст рецепта')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='image/%Y', verbose_name='Изображение рецепта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='page.category', verbose_name='Категория')),
            ],
        ),
    ]
