# Generated by Django 4.2.7 on 2023-11-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_recipe_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('text_comment', models.TextField(max_length=1000, verbose_name='Текст комментария')),
                ('active', models.BooleanField(default=True)),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='page.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
