# Generated by Django 4.2.7 on 2023-11-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_commentary_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.TextField(max_length=100, verbose_name='Название рецепта')),
                ('prompt', models.TextField(verbose_name='Текст для генерации рецепта')),
                ('text_recipe', models.TextField(verbose_name='Текст рецепта')),
            ],
            options={
                'verbose_name_plural': 'Сгенерированный рецепт',
            },
        ),
    ]
