# Generated by Django 4.2.7 on 2023-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_generate_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_recipe',
            name='ingredients',
            field=models.TextField(default=1, verbose_name='Ингредиенты'),
            preserve_default=False,
        ),
    ]
